# This is a basic workflow to help you get started with Actions

name: HOWEST CIA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
   branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '3.1.100' #SDK Version to use
    #- name: Try to build my code
     # run: dotnet build

    #- name: Run Unit tests on my code
     # run: dotnet test -v n

    - name: push to heroku
      env: 
            HEROKU_REGISTRY_URL: registry.heroku.com
            HEROKU_TOKEN : ${{ secrets.HEROKU_TOKEN }}
      run: |
            #docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
            export HEROKU_API_KEY=$HEROKU_TOKEN
            heroku container:login
            heroku container:push web --app cia-github-actions-test
            heroku container:release web --app cia-github-actions-test
            heroku ps:scale web=1 --app cia-github-actions-test
